import { InputZone, BuildingSurfaceDetailed, FenestrationSurfaceDetailed, Geometry } from "src/AppTypes"

const rooms:InputZone[] = [
  {
    "Name": "room1",
    "Multiplier": 1,
    "space_type": "office_open",
    "program": "office",
    "envelope": "concrete",
  },
  {
    "Name": "room2",
    "Multiplier": 1,
    "space_type": "office_open",
    "program": "office",
    "envelope": "concrete",
  },
  {
    "Name": "room3",
    "Multiplier": 1,
    "space_type": "office_open",
    "program": "office",
    "envelope": "concrete",
  }
]

const surfaces: BuildingSurfaceDetailed[]=[
  {
    "Surface_Type": "Wall",
    "Zone_Name": "room1",
    "Outside_Boundary_Condition": "Outdoors",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "SunExposed",
    "Wind_Exposed": "WindExposed",
    "Name": "room1_1",
    "Construction_Name": "concrete_wall",
    "vertices": [
      49.657,
      29.1,
      5,
      60.415,
      29.1,
      5,
      60.415,
      29.1,
      10,
      49.657,
      29.1,
      10
    ]
  },
  {
    "Surface_Type": "Wall",
    "Zone_Name": "room1",
    "Outside_Boundary_Condition": "Outdoors",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "SunExposed",
    "Wind_Exposed": "WindExposed",
    "Name": "room1_2",
    "Construction_Name": "concrete_wall",
    "vertices": [
      60.415,
      29.1,
      5,
      60.415,
      36.471,
      5,
      60.415,
      36.471,
      10,
      60.415,
      29.1,
      10
    ]
  },
  {
    "Surface_Type": "Wall",
    "Zone_Name": "room1",
    "Outside_Boundary_Condition": "Surface",
    "Outside_Boundary_Condition_Object": "room2_7",
    "Sun_Exposed": "NoSun",
    "Wind_Exposed": "NoWind",
    "Name": "room1_3",
    "Construction_Name": "concrete_internal_wall",
    "vertices": [
      60.415,
      36.471,
      5,
      49.657,
      36.471,
      5,
      49.657,
      36.471,
      10,
      60.415,
      36.471,
      10
    ]
  },
  {
    "Surface_Type": "Wall",
    "Zone_Name": "room1",
    "Outside_Boundary_Condition": "Outdoors",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "SunExposed",
    "Wind_Exposed": "WindExposed",
    "Name": "room1_4",
    "Construction_Name": "concrete_wall",
    "vertices": [
      49.657,
      36.471,
      5,
      49.657,
      29.1,
      5,
      49.657,
      29.1,
      10,
      49.657,
      36.471,
      10
    ]
  },
  {
    "Surface_Type": "Floor",
    "Zone_Name": "room1",
    "Outside_Boundary_Condition": "Surface",
    "Outside_Boundary_Condition_Object": "room3_19",
    "Sun_Exposed": "NoSun",
    "Wind_Exposed": "NoWind",
    "Name": "room1_5",
    "Construction_Name": "concrete_floor",
    "vertices": [
      49.657,
      29.1,
      5,
      60.415,
      29.1,
      5,
      60.415,
      36.471,
      5,
      49.657,
      36.471,
      5
    ]
  },
  {
    "Surface_Type": "Roof",
    "Zone_Name": "room1",
    "Outside_Boundary_Condition": "Outdoors",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "SunExposed",
    "Wind_Exposed": "WindExposed",
    "Name": "room1_6",
    "Construction_Name": "concrete_ceiling",
    "vertices": [
      49.657,
      29.1,
      10,
      60.415,
      29.1,
      10,
      60.415,
      36.471,
      10,
      49.657,
      36.471,
      10
    ]
  },
  {
    "Surface_Type": "Wall",
    "Zone_Name": "room2",
    "Outside_Boundary_Condition": "Surface",
    "Outside_Boundary_Condition_Object": "room1_3",
    "Sun_Exposed": "NoSun",
    "Wind_Exposed": "NoWind",
    "Name": "room2_7",
    "Construction_Name": "concrete_internal_wall",
    "vertices": [
      49.657,
      36.471,
      5,
      60.415,
      36.471,
      5,
      60.415,
      36.471,
      10,
      49.657,
      36.471,
      10
    ]
  },
  {
    "Surface_Type": "Wall",
    "Zone_Name": "room2",
    "Outside_Boundary_Condition": "Outdoors",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "SunExposed",
    "Wind_Exposed": "WindExposed",
    "Name": "room2_8",
    "Construction_Name": "concrete_wall",
    "vertices": [
      60.415,
      36.471,
      5,
      60.415,
      49.899,
      5,
      60.415,
      49.899,
      10,
      60.415,
      36.471,
      10
    ]
  },
  {
    "Surface_Type": "Wall",
    "Zone_Name": "room2",
    "Outside_Boundary_Condition": "Outdoors",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "SunExposed",
    "Wind_Exposed": "WindExposed",
    "Name": "room2_9",
    "Construction_Name": "concrete_wall",
    "vertices": [
      60.415,
      49.899,
      5,
      49.657,
      49.899,
      5,
      49.657,
      49.899,
      10,
      60.415,
      49.899,
      10
    ]
  },
  {
    "Surface_Type": "Wall",
    "Zone_Name": "room2",
    "Outside_Boundary_Condition": "Outdoors",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "SunExposed",
    "Wind_Exposed": "WindExposed",
    "Name": "room2_10",
    "Construction_Name": "concrete_wall",
    "vertices": [
      49.657,
      49.899,
      5,
      49.657,
      36.471,
      5,
      49.657,
      36.471,
      10,
      49.657,
      49.899,
      10
    ]
  },
  {
    "Surface_Type": "Floor",
    "Zone_Name": "room2",
    "Outside_Boundary_Condition": "Surface",
    "Outside_Boundary_Condition_Object": "room3_18",
    "Sun_Exposed": "NoSun",
    "Wind_Exposed": "NoWind",
    "Name": "room2_11",
    "Construction_Name": "concrete_floor",
    "vertices": [
      49.657,
      36.471,
      5,
      60.415,
      36.471,
      5,
      60.415,
      49.899,
      5,
      49.657,
      49.899,
      5
    ]
  },
  {
    "Surface_Type": "Roof",
    "Zone_Name": "room2",
    "Outside_Boundary_Condition": "Outdoors",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "SunExposed",
    "Wind_Exposed": "WindExposed",
    "Name": "room2_12",
    "Construction_Name": "concrete_ceiling",
    "vertices": [
      49.657,
      36.471,
      10,
      60.415,
      36.471,
      10,
      60.415,
      49.899,
      10,
      49.657,
      49.899,
      10
    ]
  },
  {
    "Surface_Type": "Wall",
    "Zone_Name": "room3",
    "Outside_Boundary_Condition": "Outdoors",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "SunExposed",
    "Wind_Exposed": "WindExposed",
    "Name": "room3_13",
    "Construction_Name": "concrete_wall",
    "vertices": [
      49.657,
      29.1,
      0,
      60.415,
      29.1,
      0,
      60.415,
      29.1,
      5,
      49.657,
      29.1,
      5
    ]
  },
  {
    "Surface_Type": "Wall",
    "Zone_Name": "room3",
    "Outside_Boundary_Condition": "Outdoors",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "SunExposed",
    "Wind_Exposed": "WindExposed",
    "Name": "room3_14",
    "Construction_Name": "concrete_wall",
    "vertices": [
      60.415,
      29.1,
      0,
      60.415,
      49.899,
      0,
      60.415,
      49.899,
      5,
      60.415,
      29.1,
      5
    ]
  },
  {
    "Surface_Type": "Wall",
    "Zone_Name": "room3",
    "Outside_Boundary_Condition": "Outdoors",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "SunExposed",
    "Wind_Exposed": "WindExposed",
    "Name": "room3_15",
    "Construction_Name": "concrete_wall",
    "vertices": [
      60.415,
      49.899,
      0,
      49.657,
      49.899,
      0,
      49.657,
      49.899,
      5,
      60.415,
      49.899,
      5
    ]
  },
  {
    "Surface_Type": "Wall",
    "Zone_Name": "room3",
    "Outside_Boundary_Condition": "Outdoors",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "SunExposed",
    "Wind_Exposed": "WindExposed",
    "Name": "room3_16",
    "Construction_Name": "concrete_wall",
    "vertices": [
      49.657,
      49.899,
      0,
      49.657,
      29.1,
      0,
      49.657,
      29.1,
      5,
      49.657,
      49.899,
      5
    ]
  },
  {
    "Surface_Type": "Floor",
    "Zone_Name": "room3",
    "Outside_Boundary_Condition": "Ground",
    "Outside_Boundary_Condition_Object": "",
    "Sun_Exposed": "NoSun",
    "Wind_Exposed": "NoWind",
    "Name": "room3_17",
    "Construction_Name": "concrete_floor",
    "vertices": [
      49.657,
      29.1,
      0,
      60.415,
      29.1,
      0,
      60.415,
      49.899,
      0,
      49.657,
      49.899,
      0
    ]
  },
  {
    "Surface_Type": "Ceiling",
    "Zone_Name": "room3",
    "Outside_Boundary_Condition": "Surface",
    "Outside_Boundary_Condition_Object": "room2_11",
    "Sun_Exposed": "NoSun",
    "Wind_Exposed": "NoWind",
    "Name": "room3_18",
    "Construction_Name": "concrete_ceiling",
    "vertices": [
      49.657,
      29.1,
      5,
      60.415,
      29.1,
      5,
      60.415,
      49.899,
      5,
      49.657,
      49.899,
      5
    ]
  },
  {
    "Surface_Type": "Ceiling",
    "Zone_Name": "room3",
    "Outside_Boundary_Condition": "Surface",
    "Outside_Boundary_Condition_Object": "room1_5",
    "Sun_Exposed": "NoSun",
    "Wind_Exposed": "NoWind",
    "Name": "room3_19",
    "Construction_Name": "concrete_ceiling",
    "vertices": [
      49.657,
      29.1,
      5,
      60.415,
      29.1,
      5,
      60.415,
      49.899,
      5,
      49.657,
      49.899,
      5
    ]
  }
]

const windows: FenestrationSurfaceDetailed[]=[
  {
    "Building_Surface_Name": "room1_2",
    "Surface_Type": "Window",
    "Name": "window1",
    "Construction_Name": "concrete_window",
    "vertices": [
      60.415,
      30.948,
      6.328,
      60.415,
      34.131,
      6.328,
      60.415,
      34.131,
      7.873,
      60.415,
      30.948,
      7.873
    ]
  },
  {
    "Building_Surface_Name": "room2_8",
    "Surface_Type": "Window",
    "Name": "window2",
    "Construction_Name": "concrete_window",
    "vertices": [
      60.415,
      38.565,
      7.082,
      60.415,
      41.126,
      7.082,
      60.415,
      41.126,
      8.674,
      60.415,
      38.565,
      8.674
    ]
  }
]

export const inputGeometry:Geometry={
  "BuildingSurface:Detailed": surfaces,
  "FenestrationSurface:Detailed": windows,
  "Zone": rooms,
}